import Foundation

/// Bodyweight-scaled level floors loaded from standards.json (generated by scripts/build_exercises.py).
struct StrengthStandards: Decodable {
    let reference: [String: Double]
    let allometricExponent: Double
    let levels: [String]
    let anchors: [String: Anchor]

    struct Anchor: Decodable {
        let M: [Double]
        let F: [Double]
        let load: String?
    }

    static let shared: StrengthStandards? = {
        guard let url = Bundle.main.url(forResource: "standards", withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(StrengthStandards.self, from: data)
    }()

    /// Floors for [Novice, Intermediate, Advanced, Elite, World Class] in kg of effective load.
    func floors(for standard: ExerciseStandard, sex: Sex, bodyweight: Double) -> [Double]? {
        guard let a = anchors[standard.anchor] else { return nil }
        let ratios = sex == .male ? a.M : a.F
        let ref = reference[sex.rawValue] ?? (sex == .male ? 80 : 65)
        let bw = min(max(bodyweight, 35), 200)
        let scaledRef = ref * pow(bw / ref, allometricExponent)
        return ratios.map { $0 * scaledRef * standard.factor }
    }
}

enum StrengthLevel: Int, CaseIterable, Comparable {
    case beginner, novice, intermediate, advanced, elite, worldClass
    var name: String {
        ["Beginner", "Novice", "Intermediate", "Advanced", "Elite", "World Class"][rawValue]
    }
    static func < (a: Self, b: Self) -> Bool { a.rawValue < b.rawValue }
    /// Points run 0–600: 100 per level band.
    static func from(points: Double) -> StrengthLevel {
        StrengthLevel(rawValue: min(max(Int(points / 100), 0), 5)) ?? .beginner
    }
}

struct ExerciseScore: Identifiable {
    var id: String { exerciseID }
    let exerciseID: String
    let name: String
    let e1rm: Double          // effective load, after time-off decay
    let rawE1RM: Double       // best effective load before decay
    let date: Date
    let points: Double
    let floors: [Double]
    let confidence: Double
    let muscles: [String]
    var level: StrengthLevel { .from(points: points) }
    var decayed: Bool { e1rm < rawE1RM - 0.05 }
    var nextFloor: Double? { level == .worldClass ? nil : floors[level.rawValue] }
}

struct MuscleScore: Identifiable {
    var id: String { muscle }
    let muscle: String
    let points: Double
    let best: ExerciseScore
    var level: StrengthLevel { .from(points: points) }
}

struct StrengthScoreReport {
    let exercises: [ExerciseScore]
    let muscles: [MuscleScore]
    let bodyweight: Double
    let sex: Sex
    let trainingYears: Double?

    /// Overall score: average of scored muscle groups, once at least 3 are scored.
    var score: Int? {
        guard muscles.count >= 3 else { return nil }
        return Int((muscles.map(\.points).reduce(0, +) / Double(muscles.count)).rounded())
    }
    var level: StrengthLevel? { score.map { .from(points: Double($0)) } }
    var coverage: Double { Double(muscles.count) / Double(Muscles.all.count) }
    func muscle(_ m: String) -> MuscleScore? { muscles.first { $0.muscle == m } }

    /// Typical score for someone with this many years of consistent training.
    var expectedForTrainingAge: Double? {
        guard let y = trainingYears else { return nil }
        let curve: [(Double, Double)] = [(0, 40), (0.5, 130), (1, 190), (2, 250), (3, 300), (5, 350), (8, 400), (12, 420)]
        if y >= curve.last!.0 { return curve.last!.1 }
        for i in 0..<(curve.count - 1) where y >= curve[i].0 && y < curve[i + 1].0 {
            let t = (y - curve[i].0) / (curve[i + 1].0 - curve[i].0)
            return curve[i].1 + t * (curve[i + 1].1 - curve[i].1)
        }
        return nil
    }
}

enum StrengthScoreEngine {
    static let lookbackDays = 365
    static let graceDays = 21.0
    static let decayPerWeek = 0.0075
    static let decayFloor = 0.80

    /// Strength is retained for ~3 weeks off, then drifts down slowly.
    static func decay(daysSince d: Double) -> Double {
        guard d > graceDays else { return 1 }
        return max(decayFloor, 1 - decayPerWeek * (d - graceDays) / 7)
    }

    /// Estimated 1RM of effective load. Sets of 1–10 reps use the Epley/Brzycki average; 11–15 reps
    /// use Epley (less precise, but that's where isolation work lives); bodyweight moves count up to 25.
    static func e1RM(_ info: Exercise, weight: Double, reps: Int, bodyweight: Double) -> Double? {
        guard let load = info.effectiveLoad(weight: weight, bodyweight: bodyweight), load > 0, reps >= 1 else { return nil }
        if reps <= 10 { return StrengthMath.scoringE1RM(load, reps) }
        let cap = info.trackingType == .weightReps ? 15 : 25
        return reps <= cap ? StrengthMath.epley(load, reps) : nil
    }

    static func points(_ x: Double, floors f: [Double]) -> Double {
        guard f.count == 5 else { return 0 }
        let edges = [0.0] + f
        if x >= edges[5] {
            let span = max(edges[5] - edges[4], 1)
            return min(600, 500 + 100 * (x - edges[5]) / span)
        }
        for i in 0..<5 where x >= edges[i] && x < edges[i + 1] {
            let span = edges[i + 1] - edges[i]
            return 100 * Double(i) + (span > 0 ? 100 * (x - edges[i]) / span : 0)
        }
        return 0
    }

    static func report(workouts: [Workout], library: ExerciseLibrary, profile: ProfileSnapshot,
                       asOf: Date = .now) -> StrengthScoreReport {
        let bw = profile.bodyweight(at: asOf)
        let from = asOf.addingTimeInterval(-Double(lookbackDays) * 86400)
        var bestEff: [String: (value: Double, date: Date)] = [:]
        var bestRaw: [String: Double] = [:]

        for w in workouts where w.endedAt != nil && w.startedAt >= from && w.startedAt <= asOf {
            let days = asOf.timeIntervalSince(w.startedAt) / 86400
            let k = decay(daysSince: days)
            let setBW = profile.bodyweight(at: w.startedAt)
            for ex in w.exercises {
                guard let info = library.exercise(ex.exerciseID), info.standard != nil else { continue }
                for s in ex.sets where s.completed && !s.isWarmup {
                    guard let e = e1RM(info, weight: s.weightKg, reps: s.reps, bodyweight: setBW) else { continue }
                    bestRaw[ex.exerciseID] = max(bestRaw[ex.exerciseID] ?? 0, e)
                    if e * k > (bestEff[ex.exerciseID]?.value ?? 0) {
                        bestEff[ex.exerciseID] = (e * k, w.startedAt)
                    }
                }
            }
        }

        guard let standards = StrengthStandards.shared else {
            return StrengthScoreReport(exercises: [], muscles: [], bodyweight: bw, sex: profile.sex,
                                       trainingYears: profile.trainingYears)
        }
        var scores: [ExerciseScore] = []
        for (id, b) in bestEff {
            guard let info = library.exercise(id), let std = info.standard,
                  let floors = standards.floors(for: std, sex: profile.sex, bodyweight: bw) else { continue }
            scores.append(ExerciseScore(exerciseID: id, name: info.name, e1rm: b.value, rawE1RM: bestRaw[id] ?? b.value,
                                        date: b.date, points: points(b.value, floors: floors), floors: floors,
                                        confidence: std.confidence, muscles: info.primaryMuscles))
        }
        scores.sort { $0.points > $1.points }

        var muscles: [MuscleScore] = []
        for m in Muscles.all {
            let candidates = scores.filter { $0.muscles.contains(m) }
            // Key lifts count in full; variants and machines are discounted slightly.
            guard let top = candidates.max(by: { $0.points * $0.confidence < $1.points * $1.confidence }) else { continue }
            muscles.append(MuscleScore(muscle: m, points: top.points * top.confidence, best: top))
        }
        return StrengthScoreReport(exercises: scores, muscles: muscles, bodyweight: bw, sex: profile.sex,
                                   trainingYears: profile.trainingYears)
    }

    struct HistoryPoint: Identifiable {
        var id: Date { date }
        let date: Date
        let score: Int
    }

    static func history(workouts: [Workout], library: ExerciseLibrary, profile: ProfileSnapshot,
                        weeks: Int = 26) -> [HistoryPoint] {
        let cal = Calendar.current
        return (0..<weeks).reversed().compactMap { (i: Int) -> HistoryPoint? in
            guard let d = cal.date(byAdding: .weekOfYear, value: -i, to: .now),
                  let s = report(workouts: workouts, library: library, profile: profile, asOf: d).score else { return nil }
            return HistoryPoint(date: d, score: s)
        }
    }

    /// Level for a single manual entry (used by the Strength level tool).
    static func check(exercise: Exercise, weight: Double, reps: Int, bodyweight: Double, sex: Sex) -> (points: Double, floors: [Double], e1rm: Double)? {
        guard let std = exercise.standard, let standards = StrengthStandards.shared,
              let floors = standards.floors(for: std, sex: sex, bodyweight: bodyweight),
              let e = e1RM(exercise, weight: weight, reps: reps, bodyweight: bodyweight) else { return nil }
        return (points(e, floors: floors), floors, e)
    }
}
